#cloud-config
users:
  - name: bas
    groups: sudo, docker
    shell: /bin/bash
    passwd: $6$rounds=4096$9wEEJZcpEyJ6w$Drp1eHEXD82XYacMPPAGyWW8g4uZtmwoLvouwbrR9YIpJMvQ7K45wSUfcQfldyxIgp6Al5qVwwEjSgCcx3KQH0
    ssh_authorized_keys:
      - ssh-ed2559 AAAAC3NzaC1lZDI1NTE5AAAAIPmmfO+BsW/9xuu3cd8JDfchMF0A/RTAg9bxkPooIVkQ hi@bas.sh
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD0u3WOLgalrO6eruIX01Q4+rLrP8fmMS548+p3qXTo8oNwKbRu3Fq2XonUBiwiPh9nh82QdznjN+QwNNkgpzaCodsk9Kxt6nBSNVffDiBDVoFGykrk1gDrko9ZM8+EdYYH+MAQODJxg/XyYYzdNEGkH3nrQrEtaoI3PgAMEOWcNPisuYDobAQnFRE62ioRHsZQkUb5ntK7IRVLqgAEvfWTuDKz5CE9lnoFPDVO48iXOFKzjPl6yUdfV1b6SicSA0DDwIFbhd5Yn0cCw5WzqrrCAHRBQhLtlnlDYgWL5eW/nE1gjm6cjJS3Y8y3F7+Q2cr23kGZVTsLwWzP68gPWo6tzWdBb2Nyq+H2r97xoAW+02dWlxUXSQ2Y4TV6cgiiFVc1CWbdcJP4doDrf3tOXEypt8NSNVgNGKZiYyjpe4giwluitHfM7eoGmmu/cxx8KuynVlPq/8JOlvE8AmlnVYgfMQe8eN9lBUOTFncAbfwqZOA5er03kv/S+AJTraeKz+srj0/9n7oPGTEjrmdhE5sCkBA7uWw8cbHcx3FDZbJsL8ZEhWP6hrGTQyLkogNZgWrLLjrJveeRD37KLex3nmYw6pagVKRyLK4LXBW4BqSvNsWEQdLWtg8MejvOm4kuhC+TZLnZJYxcSxnnziwuy4bZo+wfhIddfkGgnyMMETG2TQ== hi@bas.sh

apt:
  sources:
    docker.list:
      source: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable'
      keyid: 0EBFCD88

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - docker-ce
  - htop
  - neovim
  - build-essential
  - software-properties-common

runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers bas' /etc/ssh/sshd_config
  - reboot
